### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by tarrenj** [zencashio/eleos#16]
After cloning, installing npm, node.js, and nodejs-legacy, and installing electron with npm, I get the following:

tarrenj@lappy:~/Git/eleos$ npm start

> Eleos@0.0.4 start /home/tarrenj/Git/eleos
> electron .

App threw an error during load
Error: Cannot find module 'tcp-port-used'
    at Module._resolveFilename (module.js:470:15)
    at Function.Module._resolveFilename (/home/zendev/Git/eleos/node_modules/electron/dist/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/zendev/Git/eleos/main.js:9:21)
    at Object.<anonymous> (/home/zendev/Git/eleos/main.js:621:3)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
A JavaScript error occurred in the main process
Uncaught Exception:
Error: Cannot find module 'tcp-port-used'
    at Module._resolveFilename (module.js:470:15)
    at Function.Module._resolveFilename (/home/zendev/Git/eleos/node_modules/electron/dist/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/zendev/Git/eleos/main.js:9:21)
    at Object.<anonymous> (/home/zendev/Git/eleos/main.js:621:3)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)

It's possible this is user error...

**Comment by tarrenj** [comment]
This was user error.  The build instructions have been updated at https://github.com/zencashio/eleos/pull/15
